version: "3"
services:
  launchpad-postgres:
    image: postgres:15.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./init-for-dev-only.sql:/docker-entrypoint-initdb.d/init-for-dev-only.sql
    network_mode: "bridge"
  hmpps-launchpad-auth:
    build:
      context: .
    network_mode: "bridge"
    container_name: hmpps-launchpad-auth
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    env_file:
      - dev.env
    depends_on: [launchpad-postgres]


