apiVersion: batch/v1
kind: CronJob
metadata:
  name: purge-sso-requests-cronjob
spec:
#schedule: "05-55/5 06-21 * * 1-5"
  schedule: "{{ .Values.purseStaleSsoTokensSchedule }}
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 150
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: purge-sso-requests
              image: ghcr.io/ministryofjustice/hmpps-devops-tools
              args:
                - /bin/sh
                - -c
                - curl -XPOST --connect-timeout 5 --max-time 10 --retry 5 --retry-delay 0 --retry-max-time 30 http://hmpps-launchpad-auth/v1/admin/purge-stale-sso-tokens
          restartPolicy: Never