apiVersion: batch/v1
kind: CronJob
metadata:
  name: purge-inactive-users-cronjob
spec:
  schedule: "{{ .Values.purge_inactive_users_schedule }}"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: purge-inactive-users
              image: ghcr.io/ministryofjustice/hmpps-devops-tools
              args:
                - /bin/sh
                - -c
                - curl --retry 1 -XPOST http://hmpps-launchpad-auth/v1/admin/purge-inactive-users
              securityContext:
                capabilities:
                  drop:
                    - ALL
                runAsNonRoot: true
                allowPrivilegeEscalation: false
                seccompProfile:
                  type: RuntimeDefault
          restartPolicy: Never